version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: identify
    versions:
    - 1.5.13
    - 1.5.14
    - 1.6.1
    - 2.0.0
    - 2.1.0
    - 2.1.1
    - 2.1.2
    - 2.1.3
    - 2.1.4
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: regex
    versions:
    - 2020.11.13
    - 2021.3.17
  - dependency-name: virtualenv
    versions:
    - 20.4.0
    - 20.4.1
    - 20.4.2
    - 20.4.3
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: typed-ast
    versions:
    - 1.4.2
  - dependency-name: isort
    versions:
    - 5.7.0
