name: Flake8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
          architecture: x64

      - name: Install flake8
        run: pip install flake8

      - name: Flake8 action
        uses: suo/flake8-github-action@v1
        with:
          checkName: 'lint' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
